/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OperatorSettingsRouteImport } from './routes/operator.settings'
import { Route as OperatorOnlineRouteImport } from './routes/operator.online'
import { Route as OperatorNewRouteImport } from './routes/operator.new'
import { Route as OperatorConversationsRouteImport } from './routes/operator.conversations'
import { Route as OperatorAnalyticsRouteImport } from './routes/operator.analytics'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPackagesRouteImport } from './routes/app.packages'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppConversationsRouteImport } from './routes/app.conversations'
import { Route as AppCharactersRouteImport } from './routes/app.characters'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStickersRouteImport } from './routes/admin.stickers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOperatorsRouteImport } from './routes/admin.operators'
import { Route as AdminInvitesRouteImport } from './routes/admin.invites'
import { Route as AdminCreditsRouteImport } from './routes/admin.credits'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCharactersRouteImport } from './routes/admin.characters'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as AdminConversationsIndexRouteImport } from './routes/admin.conversations.index'
import { Route as OperatorChatConversationIdRouteImport } from './routes/operator.chat.$conversationId'
import { Route as AppChatConversationIdRouteImport } from './routes/app.chat.$conversationId'
import { Route as AppCharactersCharacterIdRouteImport } from './routes/app.characters.$characterId'
import { Route as AdminConversationsConversationIdRouteImport } from './routes/admin.conversations.$conversationId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperatorRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OperatorSettingsRoute = OperatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorOnlineRoute = OperatorOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorNewRoute = OperatorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorConversationsRoute = OperatorConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => OperatorRoute,
} as any)
const OperatorAnalyticsRoute = OperatorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OperatorRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagesRoute = AppPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersRoute = AppCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStickersRoute = AdminStickersRouteImport.update({
  id: '/stickers',
  path: '/stickers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperatorsRoute = AdminOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersRoute = AdminCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsIndexRoute = AdminConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConversationsRoute,
} as any)
const OperatorChatConversationIdRoute =
  OperatorChatConversationIdRouteImport.update({
    id: '/chat/$conversationId',
    path: '/chat/$conversationId',
    getParentRoute: () => OperatorRoute,
  } as any)
const AppChatConversationIdRoute = AppChatConversationIdRouteImport.update({
  id: '/chat/$conversationId',
  path: '/chat/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersCharacterIdRoute =
  AppCharactersCharacterIdRouteImport.update({
    id: '/$characterId',
    path: '/$characterId',
    getParentRoute: () => AppCharactersRoute,
  } as any)
const AdminConversationsConversationIdRoute =
  AdminConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AdminConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stickers': typeof AdminStickersRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/characters': typeof AppCharactersRouteWithChildren
  '/app/conversations': typeof AppConversationsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/conversations': typeof OperatorConversationsRoute
  '/operator/new': typeof OperatorNewRoute
  '/operator/online': typeof OperatorOnlineRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
  '/app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/operator/chat/$conversationId': typeof OperatorChatConversationIdRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stickers': typeof AdminStickersRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/characters': typeof AppCharactersRouteWithChildren
  '/app/conversations': typeof AppConversationsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/conversations': typeof OperatorConversationsRoute
  '/operator/new': typeof OperatorNewRoute
  '/operator/online': typeof OperatorOnlineRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
  '/app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/operator/chat/$conversationId': typeof OperatorChatConversationIdRoute
  '/admin/conversations': typeof AdminConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/operator': typeof OperatorRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/service': typeof ServiceRoute
  '/terms': typeof TermsRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/characters': typeof AdminCharactersRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/operators': typeof AdminOperatorsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stickers': typeof AdminStickersRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/characters': typeof AppCharactersRouteWithChildren
  '/app/conversations': typeof AppConversationsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/packages': typeof AppPackagesRoute
  '/app/profile': typeof AppProfileRoute
  '/operator/analytics': typeof OperatorAnalyticsRoute
  '/operator/conversations': typeof OperatorConversationsRoute
  '/operator/new': typeof OperatorNewRoute
  '/operator/online': typeof OperatorOnlineRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
  '/app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/app/chat/$conversationId': typeof AppChatConversationIdRoute
  '/operator/chat/$conversationId': typeof OperatorChatConversationIdRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/operator'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/service'
    | '/terms'
    | '/accept-invite/$token'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/characters'
    | '/admin/clients'
    | '/admin/conversations'
    | '/admin/credits'
    | '/admin/invites'
    | '/admin/operators'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stickers'
    | '/admin/users'
    | '/app/characters'
    | '/app/conversations'
    | '/app/favorites'
    | '/app/onboarding'
    | '/app/packages'
    | '/app/profile'
    | '/operator/analytics'
    | '/operator/conversations'
    | '/operator/new'
    | '/operator/online'
    | '/operator/settings'
    | '/admin/'
    | '/app/'
    | '/operator/'
    | '/admin/conversations/$conversationId'
    | '/app/characters/$characterId'
    | '/app/chat/$conversationId'
    | '/operator/chat/$conversationId'
    | '/admin/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/service'
    | '/terms'
    | '/accept-invite/$token'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/characters'
    | '/admin/clients'
    | '/admin/credits'
    | '/admin/invites'
    | '/admin/operators'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stickers'
    | '/admin/users'
    | '/app/characters'
    | '/app/conversations'
    | '/app/favorites'
    | '/app/onboarding'
    | '/app/packages'
    | '/app/profile'
    | '/operator/analytics'
    | '/operator/conversations'
    | '/operator/new'
    | '/operator/online'
    | '/operator/settings'
    | '/admin'
    | '/app'
    | '/operator'
    | '/admin/conversations/$conversationId'
    | '/app/characters/$characterId'
    | '/app/chat/$conversationId'
    | '/operator/chat/$conversationId'
    | '/admin/conversations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/operator'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/service'
    | '/terms'
    | '/accept-invite/$token'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/characters'
    | '/admin/clients'
    | '/admin/conversations'
    | '/admin/credits'
    | '/admin/invites'
    | '/admin/operators'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/stickers'
    | '/admin/users'
    | '/app/characters'
    | '/app/conversations'
    | '/app/favorites'
    | '/app/onboarding'
    | '/app/packages'
    | '/app/profile'
    | '/operator/analytics'
    | '/operator/conversations'
    | '/operator/new'
    | '/operator/online'
    | '/operator/settings'
    | '/admin/'
    | '/app/'
    | '/operator/'
    | '/admin/conversations/$conversationId'
    | '/app/characters/$characterId'
    | '/app/chat/$conversationId'
    | '/operator/chat/$conversationId'
    | '/admin/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OperatorRoute: typeof OperatorRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServiceRoute: typeof ServiceRoute
  TermsRoute: typeof TermsRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/operator/settings': {
      id: '/operator/settings'
      path: '/settings'
      fullPath: '/operator/settings'
      preLoaderRoute: typeof OperatorSettingsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/online': {
      id: '/operator/online'
      path: '/online'
      fullPath: '/operator/online'
      preLoaderRoute: typeof OperatorOnlineRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/new': {
      id: '/operator/new'
      path: '/new'
      fullPath: '/operator/new'
      preLoaderRoute: typeof OperatorNewRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/conversations': {
      id: '/operator/conversations'
      path: '/conversations'
      fullPath: '/operator/conversations'
      preLoaderRoute: typeof OperatorConversationsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/operator/analytics': {
      id: '/operator/analytics'
      path: '/analytics'
      fullPath: '/operator/analytics'
      preLoaderRoute: typeof OperatorAnalyticsRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packages': {
      id: '/app/packages'
      path: '/packages'
      fullPath: '/app/packages'
      preLoaderRoute: typeof AppPackagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations': {
      id: '/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/characters': {
      id: '/app/characters'
      path: '/characters'
      fullPath: '/app/characters'
      preLoaderRoute: typeof AppCharactersRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stickers': {
      id: '/admin/stickers'
      path: '/stickers'
      fullPath: '/admin/stickers'
      preLoaderRoute: typeof AdminStickersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operators': {
      id: '/admin/operators'
      path: '/operators'
      fullPath: '/admin/operators'
      preLoaderRoute: typeof AdminOperatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters': {
      id: '/admin/characters'
      path: '/characters'
      fullPath: '/admin/characters'
      preLoaderRoute: typeof AdminCharactersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations/': {
      id: '/admin/conversations/'
      path: '/'
      fullPath: '/admin/conversations/'
      preLoaderRoute: typeof AdminConversationsIndexRouteImport
      parentRoute: typeof AdminConversationsRoute
    }
    '/operator/chat/$conversationId': {
      id: '/operator/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/operator/chat/$conversationId'
      preLoaderRoute: typeof OperatorChatConversationIdRouteImport
      parentRoute: typeof OperatorRoute
    }
    '/app/chat/$conversationId': {
      id: '/app/chat/$conversationId'
      path: '/chat/$conversationId'
      fullPath: '/app/chat/$conversationId'
      preLoaderRoute: typeof AppChatConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/characters/$characterId': {
      id: '/app/characters/$characterId'
      path: '/$characterId'
      fullPath: '/app/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdRouteImport
      parentRoute: typeof AppCharactersRoute
    }
    '/admin/conversations/$conversationId': {
      id: '/admin/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/admin/conversations/$conversationId'
      preLoaderRoute: typeof AdminConversationsConversationIdRouteImport
      parentRoute: typeof AdminConversationsRoute
    }
  }
}

interface AdminConversationsRouteChildren {
  AdminConversationsConversationIdRoute: typeof AdminConversationsConversationIdRoute
  AdminConversationsIndexRoute: typeof AdminConversationsIndexRoute
}

const AdminConversationsRouteChildren: AdminConversationsRouteChildren = {
  AdminConversationsConversationIdRoute: AdminConversationsConversationIdRoute,
  AdminConversationsIndexRoute: AdminConversationsIndexRoute,
}

const AdminConversationsRouteWithChildren =
  AdminConversationsRoute._addFileChildren(AdminConversationsRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCharactersRoute: typeof AdminCharactersRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminConversationsRoute: typeof AdminConversationsRouteWithChildren
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminOperatorsRoute: typeof AdminOperatorsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStickersRoute: typeof AdminStickersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCharactersRoute: AdminCharactersRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminConversationsRoute: AdminConversationsRouteWithChildren,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminOperatorsRoute: AdminOperatorsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStickersRoute: AdminStickersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppCharactersRouteChildren {
  AppCharactersCharacterIdRoute: typeof AppCharactersCharacterIdRoute
}

const AppCharactersRouteChildren: AppCharactersRouteChildren = {
  AppCharactersCharacterIdRoute: AppCharactersCharacterIdRoute,
}

const AppCharactersRouteWithChildren = AppCharactersRoute._addFileChildren(
  AppCharactersRouteChildren,
)

interface AppRouteChildren {
  AppCharactersRoute: typeof AppCharactersRouteWithChildren
  AppConversationsRoute: typeof AppConversationsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPackagesRoute: typeof AppPackagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatConversationIdRoute: typeof AppChatConversationIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCharactersRoute: AppCharactersRouteWithChildren,
  AppConversationsRoute: AppConversationsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPackagesRoute: AppPackagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatConversationIdRoute: AppChatConversationIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OperatorRouteChildren {
  OperatorAnalyticsRoute: typeof OperatorAnalyticsRoute
  OperatorConversationsRoute: typeof OperatorConversationsRoute
  OperatorNewRoute: typeof OperatorNewRoute
  OperatorOnlineRoute: typeof OperatorOnlineRoute
  OperatorSettingsRoute: typeof OperatorSettingsRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  OperatorChatConversationIdRoute: typeof OperatorChatConversationIdRoute
}

const OperatorRouteChildren: OperatorRouteChildren = {
  OperatorAnalyticsRoute: OperatorAnalyticsRoute,
  OperatorConversationsRoute: OperatorConversationsRoute,
  OperatorNewRoute: OperatorNewRoute,
  OperatorOnlineRoute: OperatorOnlineRoute,
  OperatorSettingsRoute: OperatorSettingsRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  OperatorChatConversationIdRoute: OperatorChatConversationIdRoute,
}

const OperatorRouteWithChildren = OperatorRoute._addFileChildren(
  OperatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OperatorRoute: OperatorRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServiceRoute: ServiceRoute,
  TermsRoute: TermsRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
